# Generated by Django 4.2 on 2024-08-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
