# Generated by Django 4.2 on 2024-11-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_fullname_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Like', 'Like'), ('Comment', 'Comment'), ('Bookmark', 'Bookmark')], max_length=200),
        ),
    ]
